baseURL = "https://my-blog-bay-ten-83.vercel.app/"
languageCode = "en-us"
title = "銀河のポタージュ"
theme = "PaperMod"
[params]
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 20

[[menu.main]]
  name = "关于我"
  url = "/about/"
  weight = 5