baseURL = "https://gingapotage.vercel.app/"
languageCode = "zh"
title = "銀河のポタージュ"
theme = "PaperMod"
[params]
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true

[params.assets]
  favicon = "images/favicon.ico"
  favicon16x16 = "images/favicon-16x16.png"
  favicon32x32 = "images/favicon-32x32.png"
  apple_touch_icon = "images/apple-touch-icon.png"
  safari_pinned_tab = "images/favicon.ico"

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 20

[[menu.main]]
  name = "关于我"
  url = "/about/"
  weight = 5